version: '3'
services:

  mysqldb:
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: '123'
    image: mysql/mysql-server:8.0
    ports:
    - 13306:3306
    volumes:
    - /home/student209/test-project/db/my.cnf:/etc/my.cnf
    - /home/student209/test-project/db/data,dst=/var/lib/mysql
    - /home/student209/test-project/db/:/docker-entrypoint-initdb.d


#   backend-app:
#     depends_on:
#       - mysqldb
#     build: ./Back-end
#     restart: on-failure
#     container_name: backend-app
#     env_file: ./.env
#     ports:
#       - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#     env_file: ./.env
#     environment:
#       SPRING_APPLICATION_JSON: '{
#         "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#         "spring.datasource.username" : "$MYSQLDB_USER",
#         "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#         "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#         "spring.jpa.hibernate.ddl-auto" : "update"
#       }'
#     volumes:
#       - .m2:/root/.m2
#     stdin_open: true
#     tty: true
# volumes:
#   db: