version: '3'
services:
  
  mysqldb:
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: '123'
    image: mysql
    ports:
    - 13306:3306
    volumes:
    - ./db/my.cnf:/etc/my.cnf
    - ./db/data:/var/lib/mysql
    - ./db/:/docker-entrypoint-initdb.d
    restart: on-failure

  backend-app:
    depends_on:
      - mysqldb
    build: ./Back-end
    restart: on-failure
    container_name: backend-app
    # ports:
    #   - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.datasource.username" : "dev",
        "spring.datasource.password" : "int221",
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/bookingmodels?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.data.rest.default-media-type" : "application/json",
        "spring.hateoas.use-hal-as-default-json-media-type" : "false"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  frontend-app:
    depends_on:
      - backend-app
    build: ./Front-end
    # ports:
    #   - 80:80
    container_name: frontend-app
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/conf.d/default.conf

  proxy:
    container_name: reverse-proxy
    image: nginx
    restart: always
    depends_on:
      - frontend-app
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    
      
   


