-- MySQL Script generated by MySQL Workbench
-- Sun Apr 24 22:42:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookingmodels
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookingmodels` ;

-- -----------------------------------------------------
-- Schema bookingmodels
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookingmodels` DEFAULT CHARACTER SET utf8 ;
USE `bookingmodels` ;

-- -----------------------------------------------------
-- Table `bookingmodels`.`eventCategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookingmodels`.`eventCategories` ;

CREATE TABLE IF NOT EXISTS `bookingmodels`.`eventCategories` (
  `eventCategoryId` INT NOT NULL,
  `eventCategoryName` VARCHAR(100) NOT NULL,
  `eventCategoryDescription` TEXT(500) NULL,
  `eventCategoryDuration` INT NOT NULL,
  PRIMARY KEY (`eventCategoryId`),
  UNIQUE INDEX `eventCategoryName_UNIQUE` (`eventCategoryName` ASC) VISIBLE , 
  CONSTRAINT time_duration CHECK (eventCategoryDuration BETWEEN 1 AND 480)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookingmodels`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookingmodels`.`events` ;

CREATE TABLE IF NOT EXISTS `bookingmodels`.`events` (
  `eventId` INT NOT NULL,
  `bookingName` VARCHAR(100) NOT NULL,
  `bookingEmail` VARCHAR(50) NOT NULL,
  `eventStartTime` DATETIME NOT NULL,
  `eventDuration` INT NOT NULL ,
  `eventNotes` TEXT(500) NULL,
  `eventCategoryId` INT NOT NULL,
  PRIMARY KEY (`eventId`),
  INDEX `fk_event_eventCategory_idx` (`eventCategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_event_eventCategory`
    FOREIGN KEY (`eventCategoryId`)
    REFERENCES `bookingmodels`.`eventCategories` (`eventCategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
